# Generated by Django 4.1.7 on 2023-03-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
